name: Bug Report
description: Report a bug in an integration
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out all sections below.

  - type: dropdown
    id: integration
    attributes:
      label: Integration
      description: Which integration has the bug?
      options:
        - Unknown/General
        - Slack Notifications
        - Microsoft Teams
        - Jira Integration
        - Generic Webhook
        - Calendar Sync
        - SMTP Standard
        - Other (specify below)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure integration with...
        2. Call service...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Messages
      description: If applicable, add logs or error messages
      render: shell
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your integration configuration (redact sensitive information!)
      render: yaml
      placeholder: |
        domain: slack_notifications
        config:
          webhook_url: "https://..."
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported before
          required: true
        - label: I have checked the integration's README for known issues
          required: true


